// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace IdsMLNet_Research
{
    public partial class IdsModel
    {
        /// <summary>
        /// model input class for IdsModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"col1")]
            public string Col1 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"col2")]
            public string Col2 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"col3")]
            public string Col3 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"col4")]
            public string Col4 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"col5")]
            public string Col5 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"col6")]
            public bool Col6 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"col7")]
            public bool Col7 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"col8")]
            public bool Col8 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for IdsModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"col1")]
            public float[] Col1 { get; set; }

            [ColumnName(@"col2")]
            public float[] Col2 { get; set; }

            [ColumnName(@"col3")]
            public float[] Col3 { get; set; }

            [ColumnName(@"col4")]
            public float[] Col4 { get; set; }

            [ColumnName(@"col5")]
            public float[] Col5 { get; set; }

            [ColumnName(@"col6")]
            public float[] Col6 { get; set; }

            [ColumnName(@"col7")]
            public float[] Col7 { get; set; }

            [ColumnName(@"col8")]
            public bool Col8 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("IdsModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
